#!/bin/bash

# maim -s scr.jpg && xclip -selection clip -t image/jpg -i scr.jpg

folder=$HOME/screenshots
name=$(date +%Y-%m-%d-%H-%M-%S)".png"
grim -g "$(slurp)" $folder/$name
wl-copy < $folder/$name
